//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRating
    {
        public int RatingID { get; set; }
        public int HotelID { get; set; }
        public int CustomerID { get; set; }
        public int Ratings { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string comments { get; set; }
        public int Hospitality { get; set; }
        public int Cleanliness { get; set; }
        public int Parking { get; set; }
        public int Locality { get; set; }
        public int Taste { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
